#!/usr/bin/env python

# Usage:
#
# $ gifts <names-file>
#
# Where `<names-file>` is the file path to a newline-delimited list of names.

import sys
import random

namesFile = sys.argv[1]

def make_match(name, hat):
    result = random.sample(hat, 1)[0]
    if result == name:
      return make_match(name, hat)
    hat.remove(result)
    return result

with open(namesFile) as f:
    names = [n.strip() for n in f.readlines()]

hat = set(names)
matches = {}

for name in names:
    matches[name] = make_match(name, hat)

for name, match in matches.iteritems():
    print("{} => {}".format(name, match))

